DROP TABLE "TBL_COMMENT";
DROP TABLE "LIKE";
DROP TABLE "TBL_BOARD";
DROP TABLE "TBL_WRITER";

CREATE TABLE "TBL_BOARD" (
	"IDX"	NUMBER(6)		NOT NULL,
	"SUBJECT"	VARCHAR2(255)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"WRITER"	VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "TBL_BOARD"."IDX" IS '게시물번호';

COMMENT ON COLUMN "TBL_BOARD"."SUBJECT" IS '제목';

COMMENT ON COLUMN "TBL_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "TBL_BOARD"."DATE" IS '작성일';

COMMENT ON COLUMN "TBL_BOARD"."WRITER" IS '작성자';



CREATE TABLE "TBL_COMMENT" (
	"IDX"	NUMBER(6)		NOT NULL,
	"BIDX"	NUMBER(6)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"WRITER"	VARCHAR2(20)		NOT NULL,
	"LEVEL"	NUMBER	DEFAULT 1	NOT NULL,
	"STEP"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "TBL_COMMENT"."IDX" IS '번호';

COMMENT ON COLUMN "TBL_COMMENT"."BIDX" IS '게시글번호';

COMMENT ON COLUMN "TBL_COMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "TBL_COMMENT"."DATE" IS '작성일';

COMMENT ON COLUMN "TBL_COMMENT"."WRITER" IS '작성자';

COMMENT ON COLUMN "TBL_COMMENT"."LEVEL" IS '답글의깊이';

COMMENT ON COLUMN "TBL_COMMENT"."STEP" IS '원본글기준 답글순서';



CREATE TABLE "LIKE" (
	"IDX"	NUMBER(6)		NOT NULL,
	"WRITER"	VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE"."IDX" IS '번호';

COMMENT ON COLUMN "LIKE"."WRITER" IS '작성자';

CREATE TABLE "TBL_WRITER" (
	"WRITER"	VARCHAR2(20)		NOT NULL,
	"ID"	VARCHAR2(10)	UNIQUE NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"EMAIL_ADDRESS"	VARCHAR2(20)	UNIQUE  NOT NULL
);

COMMENT ON COLUMN "TBL_WRITER"."WRITER" IS '작성자명';

COMMENT ON COLUMN "TBL_WRITER"."ID" IS '아이디,UNIQUE';

COMMENT ON COLUMN "TBL_WRITER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "TBL_WRITER"."EMAIL_ADDRESS" IS '이메일주소,UNIQUE';

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "PK_TBL_BOARD" PRIMARY KEY (
	"IDX"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "PK_TBL_COMMENT" PRIMARY KEY (
	"IDX",
	"BIDX"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"IDX",
	"WRITER"
);

ALTER TABLE "TBL_WRITER" ADD CONSTRAINT "PK_TBL_WRITER" PRIMARY KEY (
	"WRITER"
);

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "FK_TBL_WRITER_TO_TBL_BOARD_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "TBL_WRITER" (
	"WRITER"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "FK_TBL_BOARD_TO_TBL_COMMENT_1" FOREIGN KEY (
	"BIDX"
)
REFERENCES "TBL_BOARD" (
	"IDX"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "FK_TBL_WRITER_TO_TBL_COMMENT_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "TBL_WRITER" (
	"WRITER"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_TBL_BOARD_TO_LIKE_1" FOREIGN KEY (
	"IDX"
)
REFERENCES "TBL_BOARD" (
	"IDX"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_TBL_WRITER_TO_LIKE_1" FOREIGN KEY (
	"WRITER"
)
REFERENCES "TBL_WRITER" (
	"WRITER"
);

