DROP SEQUENCE IDX_SEQUENCE;
DROP SEQUENCE CIDX_SEQUENCE;
DROP TABLE "TBL_COMMENT";
DROP TABLE "TBL_LIKE";
DROP TABLE "TBL_BOARD";
DROP TABLE "TBL_WRITER";



CREATE SEQUENCE IDX_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NOCYCLE; 
    
CREATE SEQUENCE  CIDX_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NOCYCLE; 

CREATE TABLE "TBL_BOARD" (
	"IDX"	NUMBER default IDX_SEQUENCE.nextval	NOT NULL,
	"SUBJECT"	VARCHAR2(300)		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"WDATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"ID"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TBL_BOARD"."IDX" IS '게시물번호,시퀀스';

COMMENT ON COLUMN "TBL_BOARD"."SUBJECT" IS '제목';

COMMENT ON COLUMN "TBL_BOARD"."CONTENT" IS '내용';

COMMENT ON COLUMN "TBL_BOARD"."WDATE" IS '작성일';

COMMENT ON COLUMN "TBL_BOARD"."ID" IS '아이디,UNIQUE';


CREATE TABLE "TBL_COMMENT" (
	"CIDX"	NUMBER default CIDX_SEQUENCE.nextval    NOT NULL,
	"IDX"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"WDATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"CCIDX"	NUMBER	DEFAULT 0	NULL,
	"DEPTH"	NUMBER	DEFAULT 1	NOT NULL,
	"STEP"	NUMBER	DEFAULT 1	NOT NULL,
	"ID"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TBL_COMMENT"."CIDX" IS '번호,시퀀스';

COMMENT ON COLUMN "TBL_COMMENT"."IDX" IS '게시글번호';

COMMENT ON COLUMN "TBL_COMMENT"."CONTENT" IS '내용';

COMMENT ON COLUMN "TBL_COMMENT"."WDATE" IS '작성일';

COMMENT ON COLUMN "TBL_COMMENT"."CCIDX" IS '타겟댓글번호';

COMMENT ON COLUMN "TBL_COMMENT"."DEPTH" IS '답글의깊이';

COMMENT ON COLUMN "TBL_COMMENT"."STEP" IS '원본글기준 답글순서';

COMMENT ON COLUMN "TBL_COMMENT"."ID" IS '아이디';



CREATE TABLE "TBL_LIKE" (
	"IDX"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "LIKE"."IDX" IS '번호';

COMMENT ON COLUMN "LIKE"."ID" IS '아이디,UNIQUE';

CREATE TABLE "TBL_WRITER" (
	"ID"	VARCHAR2(10)		NOT NULL,
	"WRITER"	VARCHAR2(50) UNIQUE		NOT NULL,
	"PASSWORD"	VARCHAR2(80)		NOT NULL,
	"EMAIL_ADDRESS"	VARCHAR2(250) UNIQUE	NOT NULL
);

COMMENT ON COLUMN "TBL_WRITER"."ID" IS '아이디';

COMMENT ON COLUMN "TBL_WRITER"."WRITER" IS '작성자명,UNIQUE';

COMMENT ON COLUMN "TBL_WRITER"."PASSWORD" IS '비밀번호';

COMMENT ON COLUMN "TBL_WRITER"."EMAIL_ADDRESS" IS '이메일주소,UNIQUE';

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "PK_TBL_BOARD" PRIMARY KEY (
	"IDX"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "PK_TBL_COMMENT" PRIMARY KEY (
	"CIDX",
	"IDX"
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"IDX",
	"ID"
);

ALTER TABLE "TBL_WRITER" ADD CONSTRAINT "PK_TBL_WRITER" PRIMARY KEY (
	"ID"
);

ALTER TABLE "TBL_BOARD" ADD CONSTRAINT "FK_TBL_WRITER_TO_TBL_BOARD_1" FOREIGN KEY (
	"ID"
)
REFERENCES "TBL_WRITER" (
	"ID"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "FK_TBL_BOARD_TO_TBL_COMMENT_1" FOREIGN KEY (
	"IDX"
)
REFERENCES "TBL_BOARD" (
	"IDX"
);

ALTER TABLE "TBL_COMMENT" ADD CONSTRAINT "FK_TBL_WRITER_TO_TBL_COMMENT_1" FOREIGN KEY (
	"ID"
)
REFERENCES "TBL_WRITER" (
	"ID"
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_BOARD_TO_LIKE_1" FOREIGN KEY (
	"IDX"
)
REFERENCES "TBL_BOARD" (
	"IDX"
);

ALTER TABLE "TBL_LIKE" ADD CONSTRAINT "FK_TBL_WRITER_TO_LIKE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "TBL_WRITER" (
	"ID"
);

commit;